# Generated by Django 5.2.17 on 2026-09-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scraperun',
            index=models.Index(fields=['casino', 'run_date', 'show_data'], name='scraperun_casino_date_show_idx'),
        ),
    ]
